services:
  # Servicio Web de Laravel con Docker
  - type: web
    name: backend-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: backend-guerrero
          property: host
      - key: DB_PORT
        fromDatabase:
          name: backend-guerrero
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: backend-guerrero
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: backend-guerrero
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: backend-guerrero
          property: password
      - key: APP_KEY
        generateValue: true
      - key: APP_NAME
        sync: false
      - key: APP_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      # Deploy autom√°tico
      - key: AUTO_MIGRATE
        value: true
      - key: RUN_SEEDERS
        value: true
      - key: CREATE_ADMIN_USER
        value: false
      # Credenciales del administrador
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NOMBRE
        sync: false
      - key: ADMIN_SEGUNDO_NOMBRE
        sync: false
      - key: ADMIN_APELLIDO
        sync: false
      - key: ADMIN_SEGUNDO_APELLIDO
        sync: false
      - key: ADMIN_DOCUMENTO
        sync: false
      - key: ADMIN_TELEFONO
        sync: false
      - key: ADMIN_EDAD
        sync: false
      - key: ADMIN_CAMISA
        sync: false
      - key: ADMIN_EPS
        sync: false
      - key: MAIL_MAILER
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        sync: false

databases:
  # Base de datos PostgreSQL
  - name: backend-guerrero
    databaseName: backend
    user: backend
    plan: free
